/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * squd_in
 * Full-stack SaaS with multi-tenant & RBAC.
 * OpenAPI spec version: 0.0.1
 */
import type { GetOrganizationBilling200 } from '../api.schemas'

import { fetcher } from '../../lib/fetcher'

/**
 * @summary Get billing information for an organization
 */
export type getOrganizationBillingResponse200 = {
  data: GetOrganizationBilling200
  status: 200
}

export type getOrganizationBillingResponseComposite =
  getOrganizationBillingResponse200

export type getOrganizationBillingResponse =
  getOrganizationBillingResponseComposite & {
    headers: Headers
  }

export const getGetOrganizationBillingUrl = (slug: string) => {
  return `http://localhost:3333/organizations/${slug}/billing`
}

export const getOrganizationBilling = async (
  slug: string,
  options?: RequestInit
): Promise<getOrganizationBillingResponse> => {
  return fetcher<getOrganizationBillingResponse>(
    getGetOrganizationBillingUrl(slug),
    {
      ...options,
      method: 'GET',
    }
  )
}
