/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * squd_in
 * Full-stack SaaS with multi-tenant & RBAC.
 * OpenAPI spec version: 0.0.1
 */
export type CreateAccountBody = {
  name: string
  email: string
  /** @minLength 8 */
  password: string
}

/**
 * @nullable
 */
export type CreateAccount201 =
  | (typeof CreateAccount201)[keyof typeof CreateAccount201]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAccount201 = {
  null: 'null',
} as const

export type AuthenticateWithPasswordBody = {
  email: string
  password: string
}

export type AuthenticateWithPassword201 = {
  token: string
}

export type AuthenticateWithGithubBody = {
  code: string
}

export type AuthenticateWithGithub201 = {
  token: string
}

export type RequestPasswordRecoverBody = {
  email: string
}

/**
 * @nullable
 */
export type RequestPasswordRecover201 =
  | (typeof RequestPasswordRecover201)[keyof typeof RequestPasswordRecover201]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestPasswordRecover201 = {
  null: 'null',
} as const

export type ResetPasswordBody = {
  code: string
  /** @minLength 8 */
  password: string
}

/**
 * @nullable
 */
export type ResetPassword204 =
  | (typeof ResetPassword204)[keyof typeof ResetPassword204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResetPassword204 = {
  null: 'null',
} as const

export type GetProfile200User = {
  id: string
  /** @nullable */
  name: string | null
  email: string
  /** @nullable */
  avatarUrl: string | null
}

export type GetProfile200 = {
  user: GetProfile200User
}

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMembership200MembershipRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  BILLING: 'BILLING',
} as const
export type GetMembership200Membership = {
  id: string
  organizationId: string
  userId: string
  role: (typeof GetMembership200MembershipRole)[keyof typeof GetMembership200MembershipRole]
}

export type GetMembership200 = {
  membership: GetMembership200Membership
}

export type GetOrganizationDetails200Organization = {
  id: string
  name: string
  slug: string
  /** @nullable */
  domain: string | null
  shouldAttachUsersByDomain: boolean
  /** @nullable */
  avatarUrl: string | null
  createdAt: string
  updatedAt: string
  ownerId: string
}

export type GetOrganizationDetails200 = {
  organization: GetOrganizationDetails200Organization
}

export type UpdateOrganizationBody = {
  name: string
  /** @nullable */
  domain?: string | null
  shouldAttachUsersByDomain?: boolean
}

/**
 * @nullable
 */
export type UpdateOrganization204 =
  | (typeof UpdateOrganization204)[keyof typeof UpdateOrganization204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateOrganization204 = {
  null: 'null',
} as const

/**
 * @nullable
 */
export type ShutdownOrganization204 =
  | (typeof ShutdownOrganization204)[keyof typeof ShutdownOrganization204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShutdownOrganization204 = {
  null: 'null',
} as const

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrganizations200OrganizationsItemRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  BILLING: 'BILLING',
} as const
export type GetOrganizations200OrganizationsItem = {
  id: string
  name: string
  slug: string
  /** @nullable */
  avatarUrl: string | null
  role: (typeof GetOrganizations200OrganizationsItemRole)[keyof typeof GetOrganizations200OrganizationsItemRole]
}

export type GetOrganizations200 = {
  organizations: GetOrganizations200OrganizationsItem[]
}

export type CreateOrganizationBody = {
  name: string
  /** @nullable */
  domain?: string | null
  shouldAttachUsersByDomain?: boolean
}

export type CreateOrganization201 = {
  organizationId: string
}

export type TransferOrganizationBody = {
  transferToUserId: string
}

/**
 * @nullable
 */
export type TransferOrganization204 =
  | (typeof TransferOrganization204)[keyof typeof TransferOrganization204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransferOrganization204 = {
  null: 'null',
} as const

export type GetProjectDetails200ProjectOwner = {
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  avatarUrl: string | null
}

export type GetProjectDetails200Project = {
  id: string
  description: string
  name: string
  slug: string
  /** @nullable */
  avatarUrl: string | null
  organizationId: string
  ownerId: string
  owner: GetProjectDetails200ProjectOwner
}

export type GetProjectDetails200 = {
  project: GetProjectDetails200Project
}

export type GetProjects200ProjectsItemOwner = {
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  avatarUrl: string | null
}

export type GetProjects200ProjectsItem = {
  id: string
  description: string
  name: string
  slug: string
  /** @nullable */
  avatarUrl: string | null
  organizationId: string
  ownerId: string
  createdAt: string
  owner: GetProjects200ProjectsItemOwner
}

export type GetProjects200 = {
  projects: GetProjects200ProjectsItem[]
}

export type CreateProjectBody = {
  name: string
  description: string
}

export type CreateProject201 = {
  projectId: string
}

export type UpdateProjectBody = {
  name: string
  description: string
}

/**
 * @nullable
 */
export type UpdateProject204 =
  | (typeof UpdateProject204)[keyof typeof UpdateProject204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProject204 = {
  null: 'null',
} as const

/**
 * @nullable
 */
export type DeleteProject204 =
  | (typeof DeleteProject204)[keyof typeof DeleteProject204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteProject204 = {
  null: 'null',
} as const

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrganizationMembers200MembersItemRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  BILLING: 'BILLING',
} as const
export type GetOrganizationMembers200MembersItem = {
  id: string
  userId: string
  role: (typeof GetOrganizationMembers200MembersItemRole)[keyof typeof GetOrganizationMembers200MembersItemRole]
  /** @nullable */
  name: string | null
  email: string
  /** @nullable */
  avatarUrl: string | null
}

export type GetOrganizationMembers200 = {
  members: GetOrganizationMembers200MembersItem[]
}

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMemberBodyRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  BILLING: 'BILLING',
} as const
export type UpdateMemberBody = {
  role: (typeof UpdateMemberBodyRole)[keyof typeof UpdateMemberBodyRole]
}

/**
 * @nullable
 */
export type UpdateMember204 =
  | (typeof UpdateMember204)[keyof typeof UpdateMember204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMember204 = {
  null: 'null',
} as const

/**
 * @nullable
 */
export type RemoveMember204 =
  | (typeof RemoveMember204)[keyof typeof RemoveMember204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RemoveMember204 = {
  null: 'null',
} as const

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInvitesDetails200InviteRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  BILLING: 'BILLING',
} as const
export type GetInvitesDetails200InviteOrganization = {
  name: string
}

/**
 * @nullable
 */
export type GetInvitesDetails200InviteAuthor = {
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  avatarUrl: string | null
} | null

export type GetInvitesDetails200Invite = {
  id: string
  role: (typeof GetInvitesDetails200InviteRole)[keyof typeof GetInvitesDetails200InviteRole]
  email: string
  createdAt: string
  organization: GetInvitesDetails200InviteOrganization
  /** @nullable */
  author: GetInvitesDetails200InviteAuthor
}

export type GetInvitesDetails200 = {
  invite: GetInvitesDetails200Invite
}

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInvites200InvitesItemRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  BILLING: 'BILLING',
} as const
/**
 * @nullable
 */
export type GetInvites200InvitesItemAuthor = {
  id: string
  /** @nullable */
  name: string | null
} | null

export type GetInvites200InvitesItem = {
  id: string
  role: (typeof GetInvites200InvitesItemRole)[keyof typeof GetInvites200InvitesItemRole]
  email: string
  createdAt: string
  /** @nullable */
  author: GetInvites200InvitesItemAuthor
}

export type GetInvites200 = {
  invites: GetInvites200InvitesItem[]
}

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateInviteBodyRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  BILLING: 'BILLING',
} as const
export type CreateInviteBody = {
  email: string
  role: (typeof CreateInviteBodyRole)[keyof typeof CreateInviteBodyRole]
}

export type CreateInvite201 = {
  inviteId: string
}

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPendingInvites200InvitesItemRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  BILLING: 'BILLING',
} as const
export type GetPendingInvites200InvitesItemOrganization = {
  name: string
}

/**
 * @nullable
 */
export type GetPendingInvites200InvitesItemAuthor = {
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  avatarUrl: string | null
} | null

export type GetPendingInvites200InvitesItem = {
  id: string
  role: (typeof GetPendingInvites200InvitesItemRole)[keyof typeof GetPendingInvites200InvitesItemRole]
  email: string
  createdAt: string
  organization: GetPendingInvites200InvitesItemOrganization
  /** @nullable */
  author: GetPendingInvites200InvitesItemAuthor
}

export type GetPendingInvites200 = {
  invites: GetPendingInvites200InvitesItem[]
}

/**
 * @nullable
 */
export type AcceptInvite204 =
  | (typeof AcceptInvite204)[keyof typeof AcceptInvite204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AcceptInvite204 = {
  null: 'null',
} as const

/**
 * @nullable
 */
export type RejectInvite204 =
  | (typeof RejectInvite204)[keyof typeof RejectInvite204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RejectInvite204 = {
  null: 'null',
} as const

/**
 * @nullable
 */
export type RevokeInvite204 =
  | (typeof RevokeInvite204)[keyof typeof RevokeInvite204]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RevokeInvite204 = {
  null: 'null',
} as const

export type GetOrganizationBilling200BillingSeats = {
  amount: number
  unit: number
  price: number
}

export type GetOrganizationBilling200BillingProjects = {
  amount: number
  unit: number
  price: number
}

export type GetOrganizationBilling200Billing = {
  seats: GetOrganizationBilling200BillingSeats
  projects: GetOrganizationBilling200BillingProjects
  total: number
}

export type GetOrganizationBilling200 = {
  billing: GetOrganizationBilling200Billing
}
